### ISSUE TITLE
limit 200 is not needed here:   line = ed_self.get_text_line(index, max_len=200)

### ISSUE THREAD

**Issue by Alexey-T** [jackusay/cuda_markdown_image#12]

**Comment by jackusay** [comment]
change to `get_text_line(index, 200)`?

or you mean `get_text_line(index, 0)`?

**Comment by Alexey-T** [comment]
Don’t set second parameter in all calls of get_text_line, it’s no need in markdown

**Comment by jackusay** [comment]
done. 8e1d5e1e092a2c1c128f14231cda4bfc1fc5596a
