### ISSUE TITLE
use "ed_self" instead of "ed" when setting PROP_MODIFIED

### ISSUE THREAD

**Issue by veksha** [jackusay/cuda_markdown_image#20]
found bug. PROP_MODIFIED is set to wrong tab sometimes. here is the patch:

```diff
diff --git a/__init__.py b/__init__.py
index dab5512..674baf3 100644
--- a/__init__.py
+++ b/__init__.py
@@ -114,7 +114,7 @@ class Command:
         if size_y < MIN_H: new_y = MIN_H
 
         self.add_pic(ed_self, nline, fn, size_x, size_y, ntag)
-        ed.set_prop(PROP_MODIFIED, '1')
+        ed_self.set_prop(PROP_MODIFIED, '1')
         msg_status(PRE+'Added "%s", %dx%d, line %d' % (os.path.basename(fn), size_x, size_y, nline))
 
     def add_pic(self, ed, nline, fn, size_x, size_y, ntag):

```

**Comment by veksha** [comment]
@jackusay, you can use "ed" to work with current editor (tab).
but in your case you must work with a specific editor. so it's better to avoid using of "ed" name altogether.

ed is an alias to Editor(0)

here you are using "ed" and shadowing the alias. this can bring confusion later.
`def add_pic(self, ed, nline, fn, size_x, size_y, ntag):`

@Alexey-T am I right?

**Comment by Alexey-T** [comment]
`ed` as a func parameter? possible. but not nice, it shadows the standard `ed`.

**Comment by jackusay** [comment]
ok. db9413fded05d571bce815b6da15a6677169870d
:sweat_smile:

**Comment by veksha** [comment]
very very nice :octocat:
