### ISSUE TITLE
After opening the file, for some reason, the mark "changes" is set

### ISSUE THREAD

**Issue by mrkingmidas** [jackusay/cuda_markdown_image#22]
Hello!

After opening the file, for some reason, the mark "changes" is set

Versions:
CudaText 1.190.0.0, win64-x86_64-win32, fpc 3.2.3
Plugin: 2023.04.05

**Comment by Alexey-T** [comment]
I don’t understand it. Can you be more detailed? What is mark-changes?

**Comment by mrkingmidas** [comment]
Steps:
1. In CT no files
2. Open MD file with "local" images
3. Images show, but in tab shows "changed" mark

[Demo](https://i.imgur.com/L1XYPC0.gif)

**Comment by jackusay** [comment]
I see. editor thinks cuda_markdown_image change content...

**Comment by veksha** [comment]
maybe this line:
https://github.com/jackusay/cuda_markdown_image/blob/650b3d32da6ab75cfecf47a55f57eaaccb3b7072/__init__.py#L121

**Comment by mrkingmidas** [comment]
> maybe this line:
> 
> https://github.com/jackusay/cuda_markdown_image/blob/650b3d32da6ab75cfecf47a55f57eaaccb3b7072/__init__.py#L121

Yes, after commenting this line bug gone, thank you!

**Comment by Alexey-T** [comment]
I made the fix, and another micro fix. @jackusay I will give the PR
