### ISSUE TITLE
ignore query strings like `?raw=true`, etc..

### ISSUE THREAD

**Issue by veksha** [jackusay/cuda_markdown_image#24]
https://user-images.githubusercontent.com/275333/235378813-2743b6b3-5452-4eda-b486-a4a1371a07a6.mp4

**Comment by jackusay** [comment]
`?raw=true` where is this come from? What are you try to do?

**Comment by veksha** [comment]
any url can have query string. https://en.wikipedia.org/wiki/Query_string
`?raw=true` is used in Github Markdown.

Do in CudaText console:

```python
>>> from urllib.parse import urlparse
>>> urlparse('img/screen.png')
ParseResult(scheme='', netloc='', path='img/screen.png', params='', query='', fragment='')
>>> urlparse('img/screen.png?raw=true')
ParseResult(scheme='', netloc='', path='img/screen.png', params='', query='raw=true', fragment='')
```

as you can see `urlparse` correctly separates `path` from `query`
can you use `urlparse` to do it in plugin?
or i can prepare PR?

**Comment by jackusay** [comment]
solve da00c84dfe92526a105c4a29ad3a5d1e6a3abb03

**Comment by veksha** [comment]
thanks!
