### ISSUE TITLE
write basic info to readme.txt

### ISSUE THREAD

**Issue by Alexey-T** [jackusay/cuda_markdown_image#7]
E.g.
```
This plugin finds all links to online pictures in the Markdown document, 
which may look like this:
![Stormtroopocat](https://octodex.github.com/images/stormtroopocat.jpg "The Stormtroopocat")
And it loads the linked picture and shows it inside inter-line gap,
below the text line.
```
---------

Also write the line "License: MIT" at the end

**Comment by MiroslavMatas** [comment]
not possible for local pictures?
like `![ ](file:///C:\Current Work\Service Requests\BlaBla\2023-03-09-12-30-34.png "Pic 1")`
rendering via Markdown Preview is ok for that… /sure, OS Win in this case…/

**Comment by Alexey-T** [comment]
@MiroslavMatas This is a new issue, pls move to a new topic.

**Comment by jackusay** [comment]
done.
