### ISSUE TITLE
change check for Markdown lexer

### ISSUE THREAD

**Issue by Alexey-T** [jackusay/cuda_markdown_image#9]
now: you check file extension.

needed: in install.inf file, afterr
```
[item1]
section=events
events=on_open,on_change_slow
```
add line
`lexers=Markdown`

so plugin will be loaded ONLY for markdown lexer.

**Comment by jackusay** [comment]
done. e96eb5a92ebac112c4a3a3a9d67e0fc08f284dc3

now it also works on unsaved file! cheer!
